### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by MingLi-929** [zanglab/SICER2#21]
It is a great work for developing sicer2. 
I get some bug when using sicer2.I add a new spesis of tair10 and use sicer2 to call different peak region. The bed files came from macs2
[H3ac_col0_peaks.bed.txt](https://github.com/zanglab/SICER2/files/10553857/H3ac_col0_peaks.bed.txt) and [H3ac_hda6_peaks.bed.txt](https://github.com/zanglab/SICER2/files/10553859/H3ac_hda6_peaks.bed.txt).
```
sicer_df -t ../callpeak_result/H3ac_col0/H3ac_col0_peaks.bed ../callpeak_result/H3ac_hda6/H3ac_hda6_peaks.bed -s tair10
```

the bug report laid below
```
Running SICER with given arguments 

Preprocess the H3ac_col0_peaks.bed file to remove redundancy with threshold of 1 

---------------------------------------------------------------------------------------------------------
chrom    Total plus reads        Retained plus reads       Total minus reads      Retained minus reads   
---------------------------------------------------------------------------------------------------------
1                0                        0                      10150                    10150          
2                0                        0                      8752                     8752           
3                0                        0                      9282                     9282           
4                0                        0                      8739                     8739           
5                0                        0                      9857                     9857           
Mt               0                        0                       47                       47            
Pt               0                        0                       40                       40            


Partition the genome in windows and generate summary files... 

Total count of 1 tags: 0
Total count of 1 tags: 0
Total count of 1 tags: 0
Total count of 1 tags: 0
Total count of 1 tags: 0
Total count of Mt tags: 0
Total count of Pt tags: 0


Normalizing graphs by total island filitered reads per million and generating summary WIG file...

Finding candidate islands exhibiting clustering...

Species:  tair10
Window_size:  200
Gap size:  600
E value is: 1000
Total read count: 0
Genome Length:  119667750
Effective genome Length:  88554135
Window average: 0.0
Traceback (most recent call last):
  File "/home/xiaoming/conda/miniconda3/envs/chipseq/bin/sicer_df", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/share/xiaoming/github_software/SICER2/bin/sicer_df", line 254, in <module>
    main()
  File "/share/xiaoming/github_software/SICER2/bin/sicer_df", line 249, in main
    run_SICER_df.main(args)
  File "/share/xiaoming/github_software/SICER2/sicer/main/run_SICER_df.py", line 43, in main
    temp_dir_1, library_size_file1 = run_SICER.main(args_1, True)
  File "/share/xiaoming/github_software/SICER2/sicer/main/run_SICER.py", line 77, in main
    find_islands_in_pr.main(args, total_tag_in_windows, pool)
  File "/share/xiaoming/github_software/SICER2/sicer/src/find_islands_in_pr.py", line 171, in main
    background = Background_island_probscore_statistics.Background_island_probscore_statistics(total_read_count,
  File "/share/xiaoming/github_software/SICER2/sicer/lib/Background_island_probscore_statistics.py", line 41, in __init__
    prob = self.poisson(index, self.average);
  File "/share/xiaoming/github_software/SICER2/sicer/lib/Background_island_probscore_statistics.py", line 121, in poisson
    exponent = -average + i * log(average) - self.factln(i)
ValueError: math domain error
```

**Comment by agagam** [comment]
Hi, the solution is too late for you, but it might be helpful for others. 
Check the chromosome annotations in your bams/beds with the annotations in the GenomeData.py. Change the annotations to make them the same, and it should work.
