### ISSUE TITLE
SICER2 program run error

### ISSUE THREAD

**Issue by dkur0006** [zanglab/SICER2#26]
Start
Running SICER with given arguments 

Preprocess the Panx2.bed file to remove redundancy with threshold of 1 

Removing temporary directory and all files in it.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/python/3.9.10-gcc11.2.0-rv2ln4esaesugyvk2qty4ur6nlwkbtea/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/python/3.9.10-gcc11.2.0-rv2ln4esaesugyvk2qty4ur6nlwkbtea/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/sicer2/1.0.3/sicer2-1.0.3/lib/python3.9/site-packages/sicer/src/remove_redundant_reads.py", line 133, in find_and_filter_reads
    chrom_reads = match_by_chrom(path_to_file, chrom)  # Separates all reads by chromosome
  File "/usr/local/sicer2/1.0.3/sicer2-1.0.3/lib/python3.9/site-packages/sicer/src/remove_redundant_reads.py", line 120, in match_by_chrom
    processed_reads[i] = tuple(reads)
ValueError: invalid literal for int() with base 10: '.'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/sicer2/1.0.3/sicer2-1.0.3/bin/sicer", line 235, in <module>
    main()
  File "/usr/local/sicer2/1.0.3/sicer2-1.0.3/bin/sicer", line 229, in main
    run_SICER.main(args)
  File "/usr/local/sicer2/1.0.3/sicer2-1.0.3/lib/python3.9/site-packages/sicer/main/run_SICER.py", line 52, in main
    total_treatment_read_count = remove_redundant_reads.main(args, args.treatment_file, pool)
  File "/usr/local/sicer2/1.0.3/sicer2-1.0.3/lib/python3.9/site-packages/sicer/src/remove_redundant_reads.py", line 147, in main
    filtered_result = pool.map(find_and_filter_reads_partial, chroms)
  File "/usr/local/python/3.9.10-gcc11.2.0-rv2ln4esaesugyvk2qty4ur6nlwkbtea/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/python/3.9.10-gcc11.2.0-rv2ln4esaesugyvk2qty4ur6nlwkbtea/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: invalid literal for int() with base 10: '.'
Finish

**Comment by JasonJiangs** [comment]
Hi, this should be fixed by now, I am gonna to close this issue.
