### ISSUE TITLE
Error with --significant_reads

### ISSUE THREAD

**Issue by anyang-kevin** [zanglab/SICER2#27]
Hi,
I used sicer2 to process an histone ChIP-seq data.
If I add --significant_reads, it will report the following error and I can't get output from this parament:
`multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/site-packages/sicer/src/filter_raw_tags_by_islands.py", line 27, in filter_tags_by_islands
    island_list = np.load(file_name + '_' + chrom + '_island_summary.npy', allow_pickle=True)
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'K27me3_rmDup_chr5_island_summary.npy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/bin/sicer", line 235, in <module>
    main()
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/bin/sicer", line 229, in main
    run_SICER.main(args)
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/site-packages/sicer/main/run_SICER.py", line 96, in main
    filter_raw_tags_by_islands.main(args, pool)
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/site-packages/sicer/src/filter_raw_tags_by_islands.py", line 56, in main
    pool.map(filter_tags_by_islands_partial, chroms)
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/public/home/anyang/tool/conda/miniconda3/envs/py3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'K27me3_rmDup_chr5_island_summary.npy'
`
My sicer2 version in conda is py37h97743b1_0.

**Comment by JasonJiangs** [comment]
Hi Kevin,

Sorry for the delay, it does have some problem due to some ungenerated files. We will update a new version in a short time including fixing this issue. Thanks for bring it up!

Best,
Shiyu

**Comment by EricDeveaud** [comment]
Hello, 
any news ?
I just hit the same bug 

Eric
