### ISSUE TITLE
Write error when specifying output directory

### ISSUE THREAD

**Issue by desireetillo** [zanglab/SICER2#4]
Tried running with the following commands (also had to specify .bed inputs, as I'm also getting the same bamtobed issue reported [here](https://github.com/zanglab/SICER2/issues/3)):

sicer -t test.bed -c ctrl.bed -s mm10 -cpu 16 -o sicer_out

```
Normalizing graphs by total island filitered reads per million and generating summary WIG file...

Removing temporary directory and all files in it.
Traceback (most recent call last):
  File "/usr/local/apps/sicer/2-1.0.0/bin/sicer", line 231, in <module>
    main()
  File "/usr/local/apps/sicer/2-1.0.0/bin/sicer", line 225, in main
    run_SICER.main(args)
  File "/usr/local/Anaconda/envs_app/sicer2/1.0.0/lib/python3.6/site-packages/sicer/main/run_SICER.py", line 73, in main
    make_normalized_wig.main(args, output_WIG_name, pool)
  File "/usr/local/Anaconda/envs_app/sicer2/1.0.0/lib/python3.6/site-packages/sicer/src/make_normalized_wig.py", line 46, in main
    with open(outfile_path, 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sicer_out/test-W200-normalized.wig'

```

Running without the "-o" parameter (i.e. sicer -t test.bed -c ctrl.bed -s mm10 -cpu 16) gives output and my job runs to completion.

**Comment by shahramsaghaei** [comment]
Unfortunately, I have the same issue. It is easy to handle the issue on a personal computer but to be able to run the application on a cluster output folder definition becomes necessary.
